name: pokedex
description: Pokedex app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Environment variables
  flutter_dotenv: ^5.0.2

  # Service locator
  get_it: ^7.6.0

  # Remote API client
  dio: ^5.1.2

  # State management
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # Image manipulator
  cached_network_image: ^3.2.3

  # UX/UI
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter package
  flutter_lints: ^2.0.0

  # Code generator
  build_runner: ^2.3.3
  mobx_codegen: ^2.3.0

  # Import manager
  import_sorter: ^4.6.0

  # UX/UI
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: font/Poppins-Thin.ttf
          weight: 100
        - asset: font/Poppins-ExtraLight.ttf
          weight: 200
        - asset: font/Poppins-Light.ttf
          weight: 300
        - asset: font/Poppins-Regular.ttf
          weight: 400
        - asset: font/Poppins-Medium.ttf
          weight: 500
        - asset: font/Poppins-SemiBold.ttf
          weight: 600
        - asset: font/Poppins-Bold.ttf
          weight: 700
        - asset: font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: font/Poppins-Black.ttf
          weight: 900
        - asset: font/Poppins-Italic.ttf
          style: italic
